# Generated by Django 3.0.3 on 2020-03-03 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('run_duel', '0002_auto_20200303_1154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fightevent',
            name='round',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='run_duel.Round'),
        ),
        migrations.AlterField(
            model_name='round',
            name='duel',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='run_duel.Duel'),
        ),
    ]
