# Generated by Django 3.0.3 on 2020-03-03 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('run_duel', '0003_auto_20200303_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='status',
            field=models.CharField(default='NOT STARTED', max_length=20),
        ),
    ]
