# Generated by Django 3.0.3 on 2020-03-05 11:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
        ('run_duel', '0004_round_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='duel',
            name='group',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, to='tournament.Group'),
        ),
    ]
