# Generated by Django 3.0.3 on 2020-03-08 16:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_participant'),
        ('run_duel', '0005_duel_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='duel',
            name='opponent1',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opponent1', to='tournament.Participant'),
        ),
        migrations.AlterField(
            model_name='duel',
            name='opponent2',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='opponent2', to='tournament.Participant'),
        ),
    ]
