# Generated by Django 3.0.3 on 2020-04-17 13:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('run_duel', '0006_auto_20200308_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='round',
            name='status',
        ),
    ]
